### ISSUE TITLE
Use with only camera pose and imu? 

### ISSUE THREAD

**Issue by antithing** [oysteinvolden/apriltag_state_estimation#2]
Hi, I am reading through the code and it looks like it uses apriltag poses, imu data and another source. Is this gnss?

Is it possible to run this with only camera pose/quat and imu gyro /accel data?

Thank you!

**Comment by oysteinvolden** [comment]
Yes, I use custom-defined GNSS ROS messages from this repo (sbg/ekf_quat and sbg/ekf_nav): https://github.com/SBG-Systems/sbg_ros_driver.

I also use apriltag poses this repo: from https://github.com/AprilRobotics/apriltag_ros. They are, however, converted to this format: http://docs.ros.org/en/noetic/api/geometry_msgs/html/msg/PoseWithCovarianceStamped.html before subscribed by the MEKF node. 

It is of course possible to run this filter without GNSS, it is only used to benchmark the method for application-specific experiments. In fact, I never fuse GNSS and camera pose data. I may also develop a minimal, general-purpose example at a later point.

**Comment by antithing** [comment]
Okay cool, thank you! I need to run this without ROS, so I will be pulling out the ROS dependencies and converting types. 

How do you calculate the covariance from the tag poses to use in the PoseWithCovariance type?
